### ISSUE TITLE
Can't send objects as extra data

### ISSUE THREAD

**Issue by fender** [chrisdew/jsonspace#16]
@chrisdew Double quotes are being encoded when writing this in the text input at http://127.0.0.1:8080/pubsub/user_a

`{"foo":"bar"}`

**Comment by chrisdew** [comment]
This is a shortcoming of the demo interface.

I will autodetect whether the "extra" is valid JSON, and if so, send it as such.  If not, it will remain a string.

**Comment by fender** [comment]
@chrisdew Would be great if we could prioritize this. The demo interfaces are really useful to development and testing purposes. I'm passing correct JSON into the extra field but other clients (using the demo interface) see the double quotes escaped with a back-slash.
