### ISSUE TITLE
Switching from Watch to Subscribe

### ISSUE THREAD

**Issue by fender** [chrisdew/jsonspace#18]
If I watch a channel and then subscribe to it at a later date, I don't need to get the 'subscribers' emit back.

Example:

1. I watch a channel get back "subscribers" from the websocket. I use this to populate a list of online users.
```
watch: {
  username: this.state.user.id,
  channel: this.state.user.get('language')
}
```

2. I decide to join the chat myself and do a full "subscribe". I use the same username as above for watching. I should only have 1 active websocket connection still. I don't need to get the "subscribers" list back as I was already watching.
```
subscribe: {
  username: this.state.user.id,
  channel: this.state.user.get('language'),
  extra: {
    displayName: this.state.user.get('displayName'),
    language: this.state.user.get('language'),
    ability: this.state.user.get('ability'),
    items: this.state.user.get('items'),
    abilities: abilities,
    topic: topic
  }
}
```

**Comment by chrisdew** [comment]
There is a good case for getting the subscribers list back, as it now includes you.  I'll implement this anyway.

(I am concerned about all the additional client-side code that needs to be written to save 1-10% of bandwidth by making the client remember what it's just sent (and assuming that it was successful).  I prefer the robustness of echoing the clients' actions back to them, and the client using the echo to update the client state in the same way that real event update the client state - i.e. no extra code.)

**Comment by chrisdew** [comment]
Your way of working *does* have the advantage of less apparent client latency.
