### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by fender** [chrisdew/jsonspace#19]
Do we have timeouts set up @chrisdew? The server will need to send heartbeat keepalive messages as we discussed before. I don't think I have seen a `timeout` event yet?

**Comment by chrisdew** [comment]
Not yet, I'd overlooked:
```
Use case example 3

    User subscribes to channel A
    User doesn't send a ping for over 5 minutes
    Server considers them inactive and sends a 'timeout' message to all other users in channel A to notify
```

from your email on Mon, Jan 4, 2016 at 12:23 AM.

**Comment by chrisdew** [comment]
@fender Could you clarify two points?

1. Your original request specified that the user sends the pings - is that still the case?  I'm assuming that normal traffic also keeps the timeout at bay.
2. How do timeouts and multiple subscriptions to different channels from different devices interact?

Here's a test scenario (assume a 5 minute limit):

a. user_a subscribes to #channel_0 on ws_conn_alpha
b. user_a subscribes to #channel_0 on ws_conn_beta
c. user_a subscribes to #channel_1 on ws_conn_beta
d. four minutes pass
e. user_a sends a message to #channel_0 on ws_conn_alpha
f. a minutes passes

What should happen now?

**Comment by fender** [comment]
Timeouts should only happen if the user has been inactive for 5 minutes regardless of channel. Do we even need them to subscribe to a channel for the timeout mechanism to work? Ideally as soon as they connect to the websocket we have the heartbeat/pings start. The 'timeout' message would be sent to other users for any channel that they are subscribed to.

I _think_ PubNub works by the server sending a heartbeat message every X seconds and if the client doesn't receive it then it's considered a timeout. Does that sound better than the client sending to the server?

**Comment by chrisdew** [comment]
I'd prefer the client to send the ping, as that just needs a one-way message, whereas a server-sent ping requires a response from the client to prove the connection is alive (to prove it to the server, that is).

Any traffic from the client is treated as a ping, for the purpose of deferring the time out.

Is this OK?

Can you confirm the answer to my question above is:

Nothing should happen yet, as "e" defers the time out, for user_a, another five minutes, for *all* channels to which user_a is subscribed.

**Comment by fender** [comment]
Sounds good!

**Comment by fender** [comment]
@chrisdew Moving your comment from #20 over to here.

> There are a couple of concerning things in your comment above.
> 
> The server doesn't issue a time out immediately (so considers them as still subscribed).
> Are you implying that a time out unsubscribes a user from a channel - I had previously understood it to just be an informational thing.
> 
> What are the exact semantics of a time out?
> 
> Does it cause an unsubscribe? To all channels?
> Does it close the user's websocket connections?
> But if we add in multiple devices to the mix then it could get tricky.
> We currently have no concept of "device" in pubsub, we have users and we have websocket connections.
> 
> This would be major work and has a lot of problems. Just to start:
> 
> Are devices just a name for client network addresses?
> If so, how to we handle phones with both wifi and 3G addresses (nearly all of them)?

* If a user is timed out, we definitely want to unsubscribe them from the channel. Subscribed users basically signify "online" users. So if a user times out, they are inactive and no longer considered online. Otherwise they would stay in the list indefinitely. When they come back online they will re-subscribe if required but that's handled by the client.
* A timeout should unsubscribe the user from all channels they were subscribed to.
* A timeout would only occur when the users websockets are all inactive (i.e. not pinging) so we should ensure all their websockets are closed.
* In the case that there are 2 websocket connections for a single user, don't send a timeout if one of the connections is sending pings and the other is not. Only send a time out when there is no pings at all from the user.

**Comment by chrisdew** [comment]
@fender If user_a on #channel_0, has three subscriptions, on three websocket connections, across two servers where no pings for that user_a/#channel_0 combo have been heard for X seconds, all three subscriptions should be time-out and unsubscribed?

**Comment by fender** [comment]
Yeah I suppose so. Clients aren't aware they're on 2 separate servers
though right? So there should still only be 1 unsubscribed message sent out
to everyone else.

Replication over servers worries me. It sounds complicated and I wouldn't
want to launch this buggy..

**Comment by chrisdew** [comment]
No, clients aren't made aware of which servers connections are on.  One
username on separate servers could happen, so I need to code defensively.

I'll write up the logic of distributed timeouts when I have a few minutes.
You don't need to worry about it - that's my job.

**Comment by chrisdew** [comment]
A connection level websocket timeout would be straightforward.  If this is
a acceptable alternative, it would save a few hours.

Why do timeouts need to be per-username and per-channel, rather than
per-websocket?

Why does there need to be a "timeout" message sent to watchers/subscribers.
How is this treated differently on the client from a normal "left"?

**Comment by fender** [comment]
Sorry maybe I made a mistake. All I need on my side is for other users to
know that a user has left the channel. Telling them it was a timeout isn't
important I suppose. They should only be told when the user is truly timed
out (not just 1 inactive connection if there is another one active for the
same user). Make sense?

**Comment by chrisdew** [comment]
Thanks, that clarification has probably saved 500-1000 lines of code and
tests.

I will just make websockets close if no data comes in from the client for N
minutes.  Unsubscribe and left (if no other subscriptions on other
connections) will already flow from existing logic.

**Comment by chrisdew** [comment]
note: browser's setInterval is paused when tab is in background, so background tabs may be timed-out, even when set to ping.

**Comment by chrisdew** [comment]
Use a webworker to get around this?
http://stackoverflow.com/questions/5927284/how-can-i-make-setinterval-also-work-when-a-tab-is-inactive-in-chrome/5927432#12522580

**Comment by fender** [comment]
That's fine. Timeouts don't happen for like 5 minutes right? I can live
with that.
