### ISSUE TITLE
Replace client "subscribed" and "unsubscribed" message with "joined" and "left".

### ISSUE THREAD

**Issue by chrisdew** [chrisdew/jsonspace#23]
@fender I would like to replace the client "subscribed" and "unsubscribed" messages with "joined" and "left".

The reason is that a "subscription" is a connection/username/channel thing, whereas a joined is just a username/channel thing.

Making the names different will be less confusing, as we can now talk about a username having joined a channel, and a username having subscribed to a channel on a connection.

Is this OK?

**Comment by fender** [comment]
Sure thing.

**Comment by chrisdew** [comment]
I've also changed the "subscribers" list to a "members" list.
