### ISSUE TITLE
Emit joined message for current user

### ISSUE THREAD

**Issue by fender** [chrisdew/jsonspace#26]
@chrisdew I may have asked for this to be removed before but after playing with it more, it makes sense to keep it in. Sorry for any inconvenience.

When a user subscribes to a channel, I do want to receive a `joined` message back to the same connection. I do this so the client knows that the subscription was successful and they can start to send messages.

**Comment by chrisdew** [comment]
Only the first websocket to subscribe will receive a joined response.

Is what you want a "subscribed" confirmation, in response to every "subscribe" request?

**Comment by fender** [comment]
@chrisdew Hmm I'm not getting a joined message for the first websocket to subscribe.

1. User A watches channel Foo
2. User A subscribes to channel Foo
3. User A doesn't receive a "joined" message to say that they joined channel foo <-- This needs fixing

**Comment by chrisdew** [comment]
I'll have a look at this tomorrow.

Are you still sure you want a "joined" confirmation, rather than a "subscribed" confirmation.  Only the first connection to subscribe to a channel as a given username will cause a "joined" message.

**Comment by fender** [comment]
@chrisdew Actually, I just tested this using the debugger and it seems to be working well based on the change you made yesterday! Closing again.. will re-open if I notice any issues.
