### ISSUE TITLE
Multiple watched entries

### ISSUE THREAD

**Issue by fender** [chrisdew/jsonspace#27]
@chrisdew I'm seeing duplicate entries in the `watched` debug log. It's not actually causing any issues client-side but I thought I should flag it anyway incase it's a bug waiting to explode.

This was taken from the debug log at the time of creating this issue.
```
{
  "es": [
    {
      "watched": {
        "conn_id": "websocket|146.199.72.85:60384|45.79.6.86:8888",
        "username": "5Hd0dkLtRP",
        "channel": "es"
      },
      "id": "2016-02-23T09:54:57.267Z|1|45.79.6.86|3578"
    },
    {
      "watched": {
        "conn_id": "websocket|146.199.72.85:60387|45.79.6.86:8888",
        "username": "5Hd0dkLtRP",
        "channel": "es"
      },
      "id": "2016-02-23T09:55:11.502Z|2|45.79.6.86|3578"
    }
  ]
}
```

**Comment by chrisdew** [comment]
This looks correct to me - the "es" channel is being watched by 5Hd0dkLtRP ion two *different* websocket connections.

Why do you think that this is wrong?

**Comment by fender** [comment]
I was only using a single mobile app for that user so not sure how it managed to get 2 different connections. Ah well, I don't see anything obviously wrong with it and the apps are working well now. Let's close this. :+1:
