### ISSUE TITLE
Heartbeat logic

### ISSUE THREAD

**Issue by fender** [chrisdew/jsonspace#28]
@chrisdew What is the timeout set to on the server? I've implemented a client-side ping that will occur every 5 minutes (300 seconds). So on the server could we send a timeout for a user that hasn't pinged or been active in the last 330 seconds?

**Comment by chrisdew** [comment]
The timeout is set in the configuration file of each server.  e.g. https://github.com/chrisdew/jsonspace/blob/master/pubsub/etc/45.79.6.86/pubsub.json#L4

I will change it to 330 seconds.

**Comment by fender** [comment]
Excellent, thanks.
