### ISSUE TITLE
Apple push messaging.

### ISSUE THREAD

**Issue by chrisdew** [chrisdew/jsonspace#29]
When should Apple push messages be sent?  (Specification required.)
What account credentials should be used? (Obviously, don't post them here.)

**Comment by chrisdew** [comment]
@fender This might now be working...
Currently, the message publisher is also getting a pushserver message, as it makes it easier to test.

I'm just sending a list of subscriber names to the pushserver, I don't yet know how the push server sned the messages to the right mobiles....
```
{"http_client_request":{"options":{"hostname":"localhost","port":8010,"path":"/send","method":"POST","headers":{"Content-Type":"application/json","Content-Length":354}},"data":"{\"users\":[\"user_a\"],\"android\":{\"collapseKey\":\"optional\",\"data\":{\"message\":{\"published\":{\"channel\":\"ff\",\"username\":\"user_a\",\"data\":\"test\"},\"id\":\"2016-03-02T21:57:28.257Z|0|45.79.6.86|10918\"}}},\"ios\":{\"badge\":0,\"alert\":{\"published\":{\"channel\":\"ff\",\"username\":\"user_a\",\"data\":\"test\"},\"id\":\"2016-03-02T21:57:28.257Z|0|45.79.6.86|10918\"},\"sound\":\"soundName\"}}"},"id":"2016-03-02T21:57:28.257Z|1|45.79.6.86|10918"}
SEND
SENT
STATUS: 200
HEADERS: {"x-powered-by":"Express","vary":"Accept-Encoding","date":"Wed, 02 Mar 2016 21:57:28 GMT","connection":"close","content-length":"0"}
No more data in response.
```

**Comment by chrisdew** [comment]
This is probably what I need to add to the subscribe messages: https://www.npmjs.com/package/node-pushserver#subscribe

**Comment by chrisdew** [comment]
@fender Could you see if this works for you now?

You'll need two browser windows: http://45.79.6.86:8080/pubsub/user_a and http://45.79.6.86:8080/pubsub/user_b

Put your phone's hex APN token in the subscribe request from user_a.
Subscribe user_b to the same channel and publish a message to the channel.  The message will be sent to your-phone's token.

Your phone should get the APN message.

If not, I'll add a load of message tracking code to see why it's not working.

You should see output in /var/log/upstart/pubsub.log something like:
```
{"websocket_obj_rx":{"conn_id":"websocket|81.187.221.93:49734|45.79.6.86:8888","data":{"publish":{"channel":"ff","data":"hello"}}},"id":"2016-03-09T21:46:25.067Z|0|45.79.6.86|1577"}
{"published":{"channel":"ff","username":"user_b","data":"hello","conn_id":"websocket|81.187.221.93:49734|45.79.6.86:8888"},"id":"2016-03-09T21:46:25.067Z|1|45.79.6.86|1577"}
{"websocket_obj_tx":{"conn_id":"websocket|81.187.221.93:49735|45.79.6.86:8888","obj":{"published":{"channel":"ff","username":"user_b","data":"hello"},"id":"2016-03-09T21:46:25.067Z|1|45.79.6.86|1577"}},"id":"2016-03-09T21:46:25.067Z|2|45.79.6.86|1577"}
{"apn_obj_tx":{"token":"aaaa","payload":{"published":{"channel":"ff","username":"user_b","data":"hello"},"id":"2016-03-09T21:46:25.067Z|1|45.79.6.86|1577"}},"id":"2016-03-09T21:46:25.068Z|0|45.79.6.86|1577"}
SEND
SENT
```

**Comment by fender** [comment]
@chrisdew Works perfectly. I'll need to customize the message that is sent somehow and it needs to use a value from the "extra" field of the user publishing the message.

e.g.
```js
``Message from ${extra.displayName}`
```

**Comment by chrisdew** [comment]
Would the following be useful?

Add a new, optional, property to "publish" of "apn", which is an object.

This "apn" object will override the defaults in when pubsub sends via APN.

So a publish could look like:

{
  "publish": {
    "channel": "#channel0",
    "username": "user_a",
    "data": { ...whatever you normally send... }
    "apn": {
      "badge": 3,
      "sound": "ping.aiff",
      "alert": "\uD83D\uDCE7 \u2709 You have a new message",
    }
  }
}

(I've filled the "apn" fields with the current default values, just as an
illustration.)

I think your use case could then be solved with client side code of:

var message = {
  "publish": {
    "channel": "#channel0",
    "username": "user_a",
    "data": { ...whatever you normally send... }
    "apn": {
      "alert": "Message from " + appLocalState.extra.displayName
    }
  }
}

or similar (if you were using Javascript on the client, which you're not).

I will do a similar thing for GCM, if it makes sense.

@chrisdew <https://github.com/chrisdew> Works perfectly. I'll need to
customize the message that is sent somehow and it needs to use a value from
the "extra" field of the user publishing the message.

e.g.

``Message from ${extra.displayName}`

—
Reply to this email directly or view it on GitHub
<https://github.com/chrisdew/jsonspace/issues/29#issuecomment-194761251>.

**Comment by fender** [comment]
Sounds great. Thanks Chris.
