### ISSUE TITLE
GCM push messaging

### ISSUE THREAD

**Issue by chrisdew** [chrisdew/jsonspace#30]
When should GCM push messages be sent?  (Specification required.)
What account credentials should be used? (Obviously, don't post them here.)

**Comment by chrisdew** [comment]
@fender I'm using the following confg file for pushserver:
```
{
    "webPort": 8010,
    "sqlitePath": "./pushserver.sqlite",
    "gcm": {
        "apiKey": "--redacted--"
    },
    "apn": {
        "connection": {
            "gateway": "gateway.sandbox.push.apple.com",
            "cert": "/etc/pushserver_cert.pem",
            "key": "/etc/pushserver_key.pem"
        },
        "feedback": {
            "address": "feedback.sandbox.push.apple.com",
            "cert": "/etc/pushserver_cert.pem",
            "key": "/etc/pushserver_cert.pem",
            "interval": 43200,
            "batchFeedback": true
        }
    }
}
```
Could you confirm that you can use the same config file (after putting back the gcm key) to *interactively* push messages, by pointing your browser at `http://localhost:8010`?

You'll need to start the server first with `pushserver -c config_filename.json`.

(I've renamed the certs you sent, so that I can remember what they are.)

**Comment by fender** [comment]
@chrisdew I can see the interface but can't send a push without subscribing users. I took a look at how that works and it looks like pushserver uses a mongoDB to store user tokens? Might be overkill for us and could be more effort than it is worth to ensure the tokens list is up to date (i.e. subscribe/unsubscribe users at the same time as the pubsub server). Keeping that data in 2 places opens us up to complications.

The package uses these 2 packages within it.
https://github.com/ToothlessGear/node-gcm
https://github.com/argon/node-apn

It may be way easier just to use those 2 packages so that we can send notifications directly using a device token. As mentioned before, the client can send the token and which device they use to the pubsub server perhaps within the `subscribe` method. Thoughts?

**Comment by chrisdew** [comment]
That was my original plan, so I'm happy to return to it and dump pushserver.  I'll make better enquiries next time I'm asked to spend a few hours adding and integrating another service on the servers ;-).

**Comment by fender** [comment]
@chrisdew Yeah, sometimes when I make recommendations they are not all that thought out. To be honest, I am generally terrible at anything related to Node.js. You're definitely my sensei here. :mortar_board:

**Comment by chrisdew** [comment]
@fender No problem, my fault for being too eager to just get on with the work, rather than thinking.

**Comment by chrisdew** [comment]
@fender I think we can make GCM simpler than APN as it has "topics":  https://developers.google.com/cloud-messaging/topic-messaging  The topics *seem* to act as pubsub channels.

Do you know any reason why pubsub shouldn't simply "broadcast" channel messages to GCM topics?  Topics named as per the channel name.  https://www.npmjs.com/package/node-gcm#example-application

**Comment by fender** [comment]
Looks nifty and similar to how Parse has broadcast channels for handling
its push notifications. However it'd end up being a different
implementation to what we have for APN so for now let's just implement GCM
the same as there is no throttling for number of request sent to GCM or APN.

We can look into improving in future perhaps.

**Comment by chrisdew** [comment]
OK, will make it this same as APN.

Topics would be less work on the server side (only by half an hour or so)
but I'll make it the same as APN, as perhaps it makes it easier on the
client side.

**Comment by chrisdew** [comment]
I've just thought further, and found a few edge-cases where topics would
cause trouble.

I'll do GCM the same as APN.

**Comment by chrisdew** [comment]
@fender This *might* work now.

I've tried, with an (invalid) token and get a 400 Bad Request, which at least is better than the 401 Unauthorized I got when sending with an invalid key.

```
{"gcm_obj_tx":{"token":"aa","payload":{"published":{"channel":"ff","username":"user_b","data":"da"},"id":"2016-03-14T05:56:12.752Z|1|45.79.6.86|22477"}},"id":"2016-03-14T05:56:12.754Z|0|45.79.6.86|22477"}
GCM SEND
GCM SENT
400
```

The message is put together here: https://github.com/chrisdew/jsonspace/blob/master/jsonspace/lib/protocol/gcm.js#L13

Could you test it, to see if it works with a valid token?

**Comment by chrisdew** [comment]
@fender I've noticed that you've been sending some GCMs in the logs - have they worked?

**Comment by fender** [comment]
@chrisdew No, I don't think they are being received. Push notifications sent from Parse using the same device token we used for testing do get received but those sent from pubsub do not. Where are the logs on the server? Do they tell us what's going wrong?

**Comment by chrisdew** [comment]
I'm getting an error 400 for each message sent to GCM...

**Comment by chrisdew** [comment]
I've changed to code a little and added more debugging.  
I'm no longer getting 400s - and I hope the error below is just caused by a nonsense token.
```{"websocket_obj_rx":{"conn_id":"websocket|81.187.221.90:49583|45.79.6.86:8888","data":{"publish":{"channel":"ff","data":"da","gcm":{"title":"gt"}}}},"id":"2016-03-18T06:17:44.273Z|0|45.79.6.86|32703"}
{"published":{"channel":"ff","username":"user_b","data":"da","conn_id":"websocket|81.187.221.90:49583|45.79.6.86:8888","gcm":{"title":"gt"}},"id":"2016-03-18T06:17:44.273Z|1|45.79.6.86|32703"}
{"websocket_obj_tx":{"conn_id":"websocket|81.187.221.90:49582|45.79.6.86:8888","obj":{"published":{"channel":"ff","username":"user_b","data":"da"},"id":"2016-03-18T06:17:44.273Z|1|45.79.6.86|32703"}},"id":"2016-03-18T06:17:44.274Z|0|45.79.6.86|32703"}
{"gcm_obj_tx":{"title":"gt","token":"aa","payload":{"published":{"channel":"ff","username":"user_b","data":"da"},"id":"2016-03-18T06:17:44.273Z|1|45.79.6.86|32703"}},"id":"2016-03-18T06:17:44.275Z|0|45.79.6.86|32703"}
GCM SEND
SENDING: Message {
  params:
   { notification: { title: 'gt', icon: 'ic_launcher', body: 'body' },
     data: { data: [Object] } } }
SENDING: {"params":{"notification":{"title":"gt","icon":"ic_launcher","body":"body"},"data":{"data":{"published":{"channel":"ff","username":"user_b","data":"da"},"id":"2016-03-18T06:17:44.273Z|1|45.79.6.86|32703"}}}}
to: aa
GCM SENT
{ multicast_id: 5644313775051939000,
  success: 0,
  failure: 1,
  canonical_ids: 0,
  results: [ { error: 'InvalidRegistration' } ] }
```
I think the problem was that it needed the `data` property to be an object, not a string.  So I've doubled up on the nesting.

Could you try again please?

**Comment by fender** [comment]
Hey Chris,

Some feedback from Luke, the Android dev:

   - We've got the notification now but can you set the title field to
   Kaiwa and send the notification message in the body field?
   - Also add new field 'click_action' with value set to
   'android.intent.action.MAIN' as the notification doesn't currently do
   anything when a user taps it on their device.

Hopefully this'll be the last adjustments we need.

Cheers,
Joe

**Comment by fender** [comment]
@chrisdew To add to my previous comment, I think we'll need to be able to actually specify both the title and alert message strings to be sent. So something like this:

```js
publish: {
  channel: "foo",
  data: "hi there",
  apn: {
    alert: `Message from ${me}`
  },
  gcm: {
    alert: `Message from ${me}`,
    title: "App Name"
  }
}
```

Along with the `click_action` I mentioned above, another new thing we need to pass to GCM is message `priority`. This should always be set to high, but it is normal by default.
https://developers.google.com/cloud-messaging/concept-options#setting-the-priority-of-a-message
https://github.com/ToothlessGear/node-gcm#usage

We are currently using Parse to send push notifications for some other events. However, GCM really doesn't like push notifications coming from multiple locations. Also, Parse doesn't allow us to set the message priority to high. Therefore, we're forced to move those push notifications away from the Parse back-end and on to our PubSub server instead. To do this, I am thinking we're going to need a new `notify` method. The server should then send a push notification to all connections for the given username (e.g. `bob` below). In the `apn` and `gcm` objects we can provide the same data as `publish`, i.e. an alert message and title for GCM. We also need to be able to send a `data` object to GCM and `payload` and `expiry` to APN.

```js
notify: {
  channel: "foo",
  username: 'bob',
  apn: {
    alert: 'Alert message',
    expiry: date,
    payload: { ... }
  }
  gcm: {
    alert: 'Alert message',
    title: 'App name',
    data: { ... }
  }
}
```

**Comment by fender** [comment]
@chrisdew Hey Chris, any idea when you'll have a chance to look into this last bit? We're very close now!

**Comment by fender** [comment]
@chrisdew Bump - I suppose that if we open up the apn/gcm objects to pass through any value in #40 then this issue will also be solved as we can define `click_action` and `priority` ourselves.

**Comment by chrisdew** [comment]
@fender Just to check I've understood, the outstanding work on this ticket is:

GCM: 
- let a publish.gcm.title property flow through from publish (and notify) to the GCM message
- click_action to flow through too

APN:
- nothing further needed

**Comment by fender** [comment]
@chrisdew Also for GCM, we need to set the priority to high for all messages. At the moment I think it defaults to normal?

**Comment by chrisdew** [comment]
- I've set the priority to 'high' for all messages.
- I've added click_action
- The gcm>title property was already there, which is confusing - what is the issue?

This is what is sent, when I specify title and click_action:
```js
{"websocket_obj_tx":{"conn_id":"websocket|81.187.221.93:49655|45.79.6.86:8888","obj":{"published":{"channel":"ff","username":"user_b"},"id":"2016-04-04T05:40:55.806Z|0|45.79.6.86|7864"}},"id":"2016-04-04T05:40:55.811Z|0|45.79.6.86|7864"}
{"gcm_obj_tx":{"title":"gtitle","click_action":"gca","token":"aa","payload":{"published":{"channel":"ff","username":"user_b"},"id":"2016-04-04T05:40:55.806Z|0|45.79.6.86|7864"}},"id":"2016-04-04T05:40:55.811Z|1|45.79.6.86|7864"}
GCM SEND
SENDING: Message {
  params:
   { priority: 'high',
     notification:
      { title: 'gtitle',
        icon: 'ic_launcher',
        body: 'body',
        click_action: 'gca' },
     data: { data: [Object] } } }
```

**Comment by fender** [comment]
@chrisdew Can you take a look at the logs for GCM messages? (is it possible we can see these ourselves in future?)

We're not getting any push notifications from GCM. APN is working fine. We think it's linked to a recent code change and are trying to track down the cause.

**Comment by chrisdew** [comment]
I need a UTC timestamp to look at logs.  Debugging by searching logs is hugely tedious and is only made worse by not being sure that you're even looking at the right event.  

Yes, you are welcome to look at the logs.  They are in /var/log/upstart/pubsub... and /var/log/pubsub/stopped.log.  (The current log is moved to stopped.log whenever the service is stopped or has crashed.)

I have just sent you login details.

The changes were: https://github.com/chrisdew/jsonspace/commit/76552958aeb12219a2088a580d99304743df10bc

I've remove the click_action and "priority: 'high'".  Does GCM work now?

If so, I'll reinstate "priority: 'high'" first.

**Comment by lukefanning** [comment]
@chrisdew Hi Chris, I work with @fender. I took a look at the logs and could see that the reason it wasn't working was because PubSub was reporting "bad gcm token". I checked your code and can see the the regular expression you are using to validate the token is wrong. The token can contain _ : and -

**Comment by chrisdew** [comment]
Thanks for finding this.  I'll fix it tomorrow and reintroduce the other
two features.

**Comment by lukefanning** [comment]
Soz @chrisdew you forgot to update pubsub/lib/rule/notifiedToGcm.js as well

**Comment by chrisdew** [comment]
@lukefanning Good catch.  The notify code is horrible cut-and-paste job of the publish code and should be refactored.  If I'd done that already, I wouldn't have made this mistake.
