### ISSUE TITLE
write firewall scripts for production machines

### ISSUE THREAD

**Issue by chrisdew** [chrisdew/jsonspace#31]
Features to include:
- Only allow ssh connections from trusted networks.
- Allow public access to only port 443.
- Limit port 443.
  - Limit packets per minute from *each* client IP address. (30?)
  - Limit connections per minute from *each* client IP address. (3?)
  - Limit connections per minute globally, to ease the "thundering herd" issue. (600?)
  - Limit total connections. (900 initially, until we've increased ulimit -n)

resources:
http://www.cyberciti.biz/faq/iptables-connection-limits-howto/
https://www.debian-administration.org/article/187/Using_iptables_to_rate-limit_incoming_connections
http://unix.stackexchange.com/questions/139285/limit-max-connections-per-ip-address-and-new-connections-per-second-with-iptable
http://serverfault.com/questions/754030/how-to-use-iptables-or-tc-to-limit-packets-per-client

**Comment by chrisdew** [comment]
@fender do you have any public IP addresses (or ranges) from which you will ssh into the pubsub servers?  I'll then deny public access to the ssh port (it cuts out a huge amount of log noise).

**Comment by fender** [comment]
@chrisdew I don't really plan on SSHing in to the pubsub servers. That being said, when I get back home (Monday) I could give you that IP just in case I need to at some point.
