### ISSUE TITLE
implement nginx in front of pubsub service and add HTTPS/WSS

### ISSUE THREAD

**Issue by chrisdew** [chrisdew/jsonspace#32]
@fender do you want the production websocket service to be addresses as:
a) wss://pubsub.tourney.jsonspace.com:443
b) wss://pubsub.tourney.com:443

If b) you will need to:
- add dns entries the pubsub servers as pubsub_jp.tourney.com, pubsub_tx.touney.com, etc.
- delegate pubsub.tourney.com with all the servers above as masters
- provide a certificate and private key for pubsub.tourney.com

If a) I'll set it all up, but there may be cross-domain issues to work around with any web apps.  These issues will be extra chargeable work.

Or perhaps you want it all unencrypted?

**Comment by fender** [comment]
Let's leave it all on your domain so that you have full control.

**Comment by fender** [comment]
@chrisdew Just to add: Tourney is a short way off still from having SSH and all that good stuff set up. For now, we can keep it on the jsonspace domain. When the time comes, we may need to move it, but we can cross that bridge when we get there.

**Comment by fender** [comment]
@chrisdew Will setting up these domains allow users to be routed to the nearest of the 2 servers? Currently we're just pointing directly at `ws://45.79.6.86:8888/pubsub`

**Comment by chrisdew** [comment]
Yes, pubsub.tourney.jsonspace.com will resolve to a list of all of the operation servers, listed in order of nearest to furthest.

The functionality is already tested (on an internal domain) and I hope to get the DNS set up tomorrow.
