### ISSUE TITLE
Unsubscribe and unwatch at the same time

### ISSUE THREAD

**Issue by fender** [chrisdew/jsonspace#34]
@chrisdew When a user navigates away from a specific screen on our app, we'd like to either unsubscribe or unwatch them from a channel depending on whether they subscribed or watched previously. It's not possible to store this state accurately on the client so can we have either `unsubscribe` also do an `unwatch` on the server if required? Or, add a new method like `close` which does both?

**Comment by chrisdew** [comment]
Have you tried sending both an unsubscribe and an unwatch?
If nothing matches, the command should be silently ignored.

**Comment by fender** [comment]
That's totally doable but sending 2 messages is more bandwidth than 1.
We're looking to release the apps in countries like Thailand and India
where every bit of bandwidth saved makes for a much smoother experience.

**Comment by chrisdew** [comment]
There's now an 'unwatch_and_unsubscribe' message which can be sent - it's implemented in the web interface.
