### ISSUE TITLE
Deleting old channels

### ISSUE THREAD

**Issue by fender** [chrisdew/jsonspace#35]
@chrisdew 

After a bit of testing, you can see that there are a bunch of empty channels in the debug list:
http://45.79.6.86:8080/debug/subscribed$channel

With a very active app, these would be in the 1000s very quickly. Not that it affects the client, but perhaps we should implement some cleanup for old channels? Perhaps when the last person in a channel unsubscribes you can delete the channel completely?

**Comment by chrisdew** [comment]
It is useful for debugging to see which channels have been used.  The empty arrays take up very little memory - probably just 8 or 16 bytes.  If it ever becomes an issue, it is a twenty minute fix.

**Comment by chrisdew** [comment]
@fender Are you OK with this?

**Comment by fender** [comment]
Yes, thanks.
