### ISSUE TITLE
APN title not working

### ISSUE THREAD

**Issue by fender** [chrisdew/jsonspace#36]
@chrisdew Perhaps just an issue with the debug tool? I am getting notifications correctly but when I set `apn_title` the notification message didn't use the value I set. http://45.79.6.86:8080/pubsub/user_a

**Comment by chrisdew** [comment]
Do you mean apn_alert?

**Comment by fender** [comment]
@chrisdew Yeah, sorry.

**Comment by fender** [comment]
@chrisdew It does work when sending it as `apn: { title: "..." }` manually but just not from the demo screen.

**Comment by chrisdew** [comment]
There is no APN "title" property, only "alert".

If you sent ..."apn":{"title":"foo"}... it would just be ignored by the
code below:

https://github.com/chrisdew/jsonspace/blob/master/jsonspace/lib/protocol/apn.js

Are you sending the "apn":{"title":...} as part of a "subscribe" or as part
of a "publish"?

I'll spend some time on this tomorrow.

**Comment by fender** [comment]
@chrisdew Sorry, that was me writing it incorrect. `apn: { alert: "..." }` works fine when adding it to the publish message. However, the issue is the text field on the debug page didn't work. The `apn_alert` one below in the screenshot. That's all that is wrong here.

![screen shot 2016-03-15 at 17 20 52](https://cloud.githubusercontent.com/assets/1436470/13787093/68bb828c-ead2-11e5-8f09-938518407242.png)

**Comment by chrisdew** [comment]
@fender All caused by missing two hashes: https://github.com/chrisdew/jsonspace/commit/8df36c1e16d42042af20c103f2d1c003ce1f0da3#diff-1f0777864933977e499babf1811ee7ebL197
