### ISSUE TITLE
Specify APN certificates and GCM token 

### ISSUE THREAD

**Issue by fender** [chrisdew/jsonspace#37]
Not immediately, but in the near future we're going to need to handle multiple APN certificates and GCM tokens for push notifications. Dev and production credentials differ as well as different apps. How would we go about this? Perhaps we could set up a config on the server that maps a specific string key to a set of credentials and then pass that key in with the apn/gcm objects?

e.g.
```js
publish: {
  channel: "foo",
  data: "hi there",
  apn: {
    alert: `Message from ${me}`,
    cert: "tourney-dev"
  },
  gcm: {
    alert: `Message from ${me}`,
    title: "App Name",
    key: "tourney-dev"
  }
}
```

**Comment by chrisdew** [comment]
Yes, I'll do this.

I'm not going to add alternative configs, as that will take a lot more work than just letting you choose the gcm key and apn cert and key directly.

Their configs currently look like this:
```
  {"protocol":{"apn":{"listen":{"options":{"cert":"/etc/apn_cert.pem","key":"/etc/apn_key.pem"}}}}},
  {"protocol":{"gcm":{"listen":{"options":{"key":"--redacted--"}}}}},
```

So to keep "publish" consistent, overriding the apn/gcm defaults will look like this:
```
publish: {
  channel: "foo",
  data: "hi there",
  apn: {
    alert: `Message from ${me}`,
    options: {
      cert:"/etc/apn_cert.pem",
      key:"/etc/apn_key.pem"
    }
  },
  gcm: {
    alert: `Message from ${me}`,
    title: "App Name",
    options: {
      key: "--redacted--"
    }
  }
}
```
This is not implemented yet...

**Comment by chrisdew** [comment]
P.S. Having a "listen" in the protocol configurations for non-listening apn and gcm is horrible, and will be renamed, probably to "connect" or similar.

**Comment by fender** [comment]
@chrisdew Sounds good to me.
