### ISSUE TITLE
"notify" message for GCM and APN

### ISSUE THREAD

**Issue by chrisdew** [chrisdew/jsonspace#40]
Copied from: https://github.com/chrisdew/jsonspace/issues/30#issuecomment-199741705

We are currently using Parse to send push notifications for some other events. However, GCM really doesn't like push notifications coming from multiple locations. Also, Parse doesn't allow us to set the message priority to high. Therefore, we're forced to move those push notifications away from the Parse back-end and on to our PubSub server instead. To do this, I am thinking we're going to need a new `notify` method. The server should then send a push notification to all connections for the given username (e.g. `bob` below). In the `apn` and `gcm` objects we can provide the same data as `publish`, i.e. an alert message and title for GCM. We also need to be able to send a `data` object to GCM and `payload` and `expiry` to APN.

```js
notify: {
  channel: "foo",
  username: 'bob',
  apn: {
    alert: 'Alert message',
    expiry: date,
    payload: { ... }
  }
  gcm: {
    alert: 'Alert message',
    title: 'App name',
    data: { ... }
  }
}
```

**Comment by chrisdew** [comment]
@fender You can already do something similar by making eacj client subscribe to a channel which is unique for the username and/or device name.

E.g. is your channels are normally called '#channel_a', subscribe to a channel called '$username_imei' or similar, from each device.

Note: you do not need to subscribe to a channel to send messages to a channel.

Will this work for you?

**Comment by fender** [comment]
@chrisdew It could possibly work if we could also set custom JSON objects within published messages that get passed along with the notification as payload/data params.

However, we'd need to ensure the user is always subscribed to their own personal channel too which means more websocket messages need to be sent upon loading/reconnection/unloading. I'm trying to maintain as little bandwidth usage as possible for our apps and so having this `notify` message or similar would prevent the need for that extra thing to worry about on the client-side.

**Comment by chrisdew** [comment]
OK, I'll do this so that you don't require username subscriptions.

Can you explain the significance of "channel" in the "notify"?  If the user hasn't subscribed to the channel, they shouldn't be notified?

Why are the APN payload and GCM data separate properties, and not just a "data" property directly in the "notify"?

I'm wondering whether I shouldn't just provide external access to apn_obj_tx and gcm_obj_tx directly from the client and let you send what you like.  e.g.
```
{"gcm_obj_tx":{"title":"Message from Delorean Dynamite","token":"--redacted--","payload":{"published":{"channel":"C6CKAQ6HF8","username":"R6EmkAVgYy","data":"4*"},"id":"2016-03-27T14:29:43.694Z|0|45.79.6.86|25982"}},"id":"2016-03-27T14:29:43.694Z|2|45.79.6.86|25982"}
```

**Comment by fender** [comment]
Good question. Channel isn't actually necessary. Just username.

Yeah a single object would reduce the message size. I don't think there is
any case where we need to send separate date. Being able to have external
access would work too. Let me know when this is done so I can test, thanks!

**Comment by fender** [comment]
@chrisdew So if we go with allowing external access, it makes it much easier for clients to tweak things in future. I assume this would also work the same for `published` message objects?

**Comment by chrisdew** [comment]
> Good question. Channel isn't actually necessary. Just username.
Just realised channel is necessary, as subscribers *could* specify different tokens in different channels.

> So if we go with allowing external access, it makes it much easier for clients to tweak things in future. I assume this would also work the same for published message objects?
I don't think I like where this is heading (making clients dependent on internals of pubsub will constrain pubsub implementation, and break clients when refactoring), so I'll implement a notify message as:
```js
notify: {
  channel: "foo",
  username: 'bob',
  apn: {
    alert: 'Alert message'
  }
  gcm: {
    title: 'App name',
  }
  data: ...
}
```

**Comment by chrisdew** [comment]
At the moment, you will need to have subscribed to a channel to send notification to a user on that channel.  Is this expected and OK?
