### ISSUE TITLE
Notify messages not being sent

### ISSUE THREAD

**Issue by fender** [chrisdew/jsonspace#42]
@chrisdew From your debug page I am able to send a notification message successfully. This worked correctly:
```
sent:{"notify":{"channel":"es","data":"Test data","username":"nYys6lrYoF","apn":{"alert":"test"}}}
```

However, when I try to send it through a websocket from one client to another it is not working.
```js
WebSocketActions.sendMessage({
  notify: {
    channel: 'es',
    username: 'nYys6lrYoF',
    data: 'test'
    apn: {
      alert: 'Boo'
    },
  }
});
```

Can you check the logs to see if there is an error on the server-side or something I am missing? I can't seem to figure out where the issue lies.

**Comment by chrisdew** [comment]
Can you tell me the UTC time of when these non-debug-page messages were sent?

**Comment by chrisdew** [comment]
P.S. The web page uses websockets too, so there's really no difference.  Have you subscribed to the channel on which you are sending the notify?

**Comment by fender** [comment]
It would have been the last notify message sent, quite shortly before
creating this GitHub issue. Sorry, don't have an exact time stamp.

Not subscribing before sending a notify although I did try and that didn't
help.

**Comment by chrisdew** [comment]
You need to subscribe to a channel, before sending a notify on that channel.

I will spend some time searching the logs on Wednesday.

**Comment by fender** [comment]
@chrisdew Ok, I think our app logic can accommodate subscribe before notify so will give that another whirl now and let you know how it goes.

**Comment by fender** [comment]
@chrisdew Thanks Chris, it worked. Sorry about that!

**Comment by chrisdew** [comment]
No problem.
