### ISSUE TITLE
Members last seen timestamp

### ISSUE THREAD

**Issue by fender** [chrisdew/jsonspace#43]
@chrisdew Is it possible to include a last seen timestamp to each member in the `members` list sent after a subscribe as well as the `joined` and `left` messages? We're hoping to order the subscribed users list by the the most recently active at the top. I am assuming you already have this time timestamp for the timeout functionality?

**Comment by chrisdew** [comment]
I don't yet understand this.  The client only gets the members list when it subscribes, so the last-seen timestamps will get stale.

Will each published message, received by a clinet, cause the local last-seen timestamp to be updated?

What counts as activity?  Published message only, or subscribing too.

If only published messages, then what should the timestamp of lurkers be?

**Comment by fender** [comment]
Ugh, good point. We can't really keep it in sync after the join. Apologies,
I overlooked that. So, to simplify, could we just make sure that the
members list returns the subscribers in the ordered that they joined
(ascending). So the first user to subscribe ends up at the bottom of the
members list and the most recent at the top. Perhaps that's already the
case?

**Comment by chrisdew** [comment]
I think that they may, accidentally, be in order of
earliest-to-subscribe-first.

**Comment by fender** [comment]
Excellent, closing. 👍
