### ISSUE TITLE
Connection closed should respect timeout

### ISSUE THREAD

**Issue by fender** [chrisdew/jsonspace#44]
@chrisdew When an iPhone goes to sleep (by default after 30seconds, or when hitting the power button) it automatically closes any websocket to save battery. If I'm not mistaken, the pubsub server is issuing a `left` message as soon as a connection is broken. However, we don't want this unless there is a deliberate `unsubscribe` or a `timeout`.

**Comment by chrisdew** [comment]
This is a very big deal which breaks the currently implemented model.  At a rough guess, I fear it would be several days of work and testing, as it would affect nearly all the code.  I will think about this for a while before panicking too badly.

**Comment by chrisdew** [comment]
Thinking about this further, it *may* be possible to make the 'unsubscribe on disconnect' rule optional and implement a timeout rule instead of relying on the socket disconnect.

This would only be half a day's work.  As this would be an optional feature I would not to have to rewrite all the tests (which would have made them useless anyway, as they would no longer have seen 'left' messages etc.).

**Comment by fender** [comment]
@chrisdew Sorry, had no idea this was such a big undertaking. The underlying issue is that other clients do not know if the user that `left` did it on purpose or not. So, perhaps you can either issue a `dropped` message when a socket connection is broken and continue to have the `left` when someone does an `unsubscribe`? Or do you have any other ideas? The least amount of work here possible would be best.

Another idea I have would be that when someone purposefully unsubscribes from a channel, they publish a message just before-hand with data `__LEAVING__` and other users can listen to that. However, I would like to try to avoid sending that extra message if possible.

**Comment by fender** [comment]
@chrisdew Also, quick question, a `timeout` will be issued after 5 minutes of there being no messages sent over an _open_ connection?

**Comment by chrisdew** [comment]
@fender Yes, there is timeout code on the websocket: 
https://github.com/chrisdew/jsonspace/blob/master/jsonspace/lib/protocol/websocket.js#L41

Which is set via config: 
https://github.com/chrisdew/jsonspace/blob/master/pubsub/etc/pubsub.json#L3

When the websocket times out, it is closed by the server:
https://github.com/chrisdew/jsonspace/blob/master/jsonspace/lib/protocol/websocket.js#L46

There is nothing to stop the client reconnecting, if it wishes.

Note: a timeout could not logically just unsubscribe a client, as the client makes assumptions about the fact that it *always* successfully subscribes and is never forefully  unsubscribed, as opposed to using the (removed) server replies to inform it about subscription statuses.

**Comment by chrisdew** [comment]
I think I've found a hack which can solve this problem without extensive rewrites.

I've replaced the "unsubscribedOnDisconnected" rule with an "unsubscribedOnDisconnectedDelayed" rule which doesn't send the "unsubscribed" until a delay has expired.
https://github.com/chrisdew/jsonspace/blob/master/pubsub/lib/rule/unsubscribedOnDisconnectDelayed.js

This has two side effects:

Published messages will be routed to the closed websocket transmitting code, which will log an error as the websocket is already closed.
https://github.com/chrisdew/jsonspace/blob/master/jsonspace/lib/protocol/websocket.js#L56

The timeout behaviour of websockets will take longer to remove a stale username with only one connection, as both the websocket idle tiemout will need to elapse *and* the  unsubscribedOnDisconnectedDelayed's DELAY will need to expire, sequentially.

Is this all OK?  The code is already on the servers for testing.

**Comment by chrisdew** [comment]
I've just tested it with browser tabs, and it looks good.  Explicit "unsubscribes" cause the other members of the channel to get a "left" immediately.  Websocket-closure-initiated  (i.e. tab closed) "unsubscribed"s cause a "left" message, after a minute.

The 60-second delay is hard-coded in the "unsubscribedOnDisconnectedDelayed" rule, as I don't currently have a way to pass parameters from config to rules.  (This is the first time I've needed such a feature.)

Let me know if you would like the delay changed.

**Comment by fender** [comment]
@chrisdew Glad you found a quick fix. A couple of adjustments:
* Please make the delay for `unsubscribedOnDisconnect` the same as the timeout config value
* In `unsubscribedOnDisconnect` do not do the delay if the connection was closed via a timeout, instead just do it instantly.

**Comment by fender** [comment]
@chrisdew Also, random thought. With this new `unsubscribedOnDisconnect` logic, is there still a purpose to `timeout` and `ping`? The initial idea was that we wanted users to have a 'grace period' where they can reconnect without everyone else being told they left. Unless it is possible to have stale connections with WebSockets even after the client has disconnected, then this new logic may just cover all our requirements.

**Comment by chrisdew** [comment]
Yes, stale connections, where the client has disconnected but the server
doesn't know, will always be with us.  Timeout needs to stay.

**Comment by fender** [comment]
@chrisdew Ok. Just checking, did you see my comment above with the 2 alterations we need? This issue is closed but I can't re-open.

**Comment by fender** [comment]
Bump! We're going to need this for next weeks launch. 🙏

**Comment by fender** [comment]
@chrisdew This issue is getting quite long and difficult to follow. Going to close this and email you.
