### ISSUE TITLE
Load maintenance

### ISSUE THREAD

**Issue by fender** [chrisdew/jsonspace#45]
@chrisdew We're aiming to launch our first product on this next week - Tourney (web version). I'm always worried about spikes in traffic and servers failing. We had several times when the BC node JS server went down at launch without us knowing. I would like to ensure this doesn't happen for Tourney. A few questions:

1. If I remember correctly, you've set a maximum number of simultaneous clients. How many is that and what happens if it is reached?
2. How can we monitor server load so that we know if we're stressing the server?
3. Can we be alerted if there is a server down? Something like https://www.pingdom.com/ perhaps?

May be a little early to expect the servers to get much load but better safe than sorry!

**Comment by chrisdew** [comment]
1. The servers have a ulimit of 20K file handles.  If this is reached, no more clients can connect.
2. Server load can be seen from Linode, I'll investigate what we can get from them for free.
3. I'm implementing an email alert in jsonspace.  Each server will watch the other, and if too many heartbeats are missed, an email will be sent.

**Comment by chrisdew** [comment]
Email alerts implemented for server start, replication connect, replication disconnect and replication error.
