### ISSUE TITLE
Extending notifiy

### ISSUE THREAD

**Issue by fender** [chrisdew/jsonspace#47]
@chrisdew How easy/hard would it be to extend `notify` so that as well as sending push notifications, it also sends a message directly to all connections with the given `username` in the `channel`? We've ran into an issue where its possible that APN or GCM may delay sending a notification, and we'd like WebSockets as a fallback when the app is in the foreground.

Alternatively, we can just publish a message to the channel at the same time as the `notify` but then its sent to all users and so we have to filter it out.

**Comment by chrisdew** [comment]
That should take about five minutes - I just need to put back a couple of
lines which I removed when I copied "publish".
