### ISSUE TITLE
GCM notification sound & tag

### ISSUE THREAD

**Issue by lukefanning** [chrisdew/jsonspace#50]
@chrisdew Hi Chris, me again :), small issue this time. GCM push notifications are silent by default unless ``sound: 'default'`` is set on the notification object. Be great if you could add that! Making it customisable would be good as well as it is possible to set a custom sound but I don't think we'd ever need that.

We also need a customisable``tag`` string value added to the notification object as well. This means new notifications can replace existing ones. At the moment for every message sent a new notification is displayed in the notification center.

**Comment by chrisdew** [comment]
You *should* now be able to add values for `sound`, `tag` and `color` to the `gcm` object when publishing or notifying.

e.g.
```
"gcm": {
  ...
  "sound":"default",
  "tag":"foo",
  ...
}
```
I will test it later, but you may get there first.

**Comment by fender** [comment]
@chrisdew We got it working thanks, can close this if you want.
