### ISSUE TITLE
Android SSL Error

### ISSUE THREAD

**Issue by lukefanning** [chrisdew/jsonspace#51]
@chrisdew Connectivity to wss://pubsub.tourney.jsonspace.com/pubsub is currently broken on Android due to an issue with SSL. Android reports:

```java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.```

Running ```openssl s_client -connect pubsub.tourney.jsonspace.com:443``` displays:

Loading 'screen' into random state - done
CONNECTED(00000084)
depth=0 /OU=Domain Control Validated/OU=PositiveSSL/CN=pubsub.tourney.jsonspace.com
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 /OU=Domain Control Validated/OU=PositiveSSL/CN=pubsub.tourney.jsonspace.com
verify error:num=27:certificate not trusted
verify return:1
depth=0 /OU=Domain Control Validated/OU=PositiveSSL/CN=pubsub.tourney.jsonspace.com
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:/OU=Domain Control Validated/OU=PositiveSSL/CN=pubsub.tourney.jsonspace.com
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA

(This is not the complete output of the openssl command.. let me know if you need it)

**Comment by lukefanning** [comment]
From a bit of Googling it appears as though you need to install an intermediate certificate(s).

**Comment by chrisdew** [comment]
Your diagnosis is most likely correct, I've had to add intermediate certs before.  

I need to try a few different OSs/browsers to find one which needs an intermediate cert for this cert, otherwise I will not be able to tell if I've fixed it.  (OSX/Firefox is happy as is.)

**Comment by fender** [comment]
@chrisdew I think iOS also isn't happy with the cert. I'm in debug mode so it allows me through.
`SocketRocket: In debug mode.  Allowing connection to any root cert`

**Comment by chrisdew** [comment]
I've found and downloaded the intermediate certs that Android needs, and I'll install them later.

**Comment by fender** [comment]
Have you looked into iOS? Or do they use the same ones?

**Comment by chrisdew** [comment]
Can you try https again now?  I've added three intermediate certs, following instructions on https://gist.github.com/bradmontgomery/6487319

**Comment by fender** [comment]
@chrisdew I'm still seeing a warning when connecting to the websocket on iOS. If I wasn't running in debug mode it would likely refuse connection.
`SocketRocket: In debug mode.  Allowing connection to any root cert`

**Comment by lukefanning** [comment]
@chrisdew This is working fine now on Android. @fender Sure it doesn't always say that when connecting to a secure WebSocket regardless of the actual certs?

**Comment by fender** [comment]
@lukefanning Yeah, perhaps. How can I test that?

**Comment by lukefanning** [comment]
@fender Not sure yet. I ran ```openssl``` again with these results:

Loading 'screen' into random state - done
CONNECTED(000001E0)
depth=3 /C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
verify error:num=19:self signed certificate in certificate chain
verify return:0
---
Certificate chain
 0 s:/OU=Domain Control Validated/OU=PositiveSSL/CN=pubsub.tourney.jsonspace.com
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
 1 s:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Certification Authority
 2 s:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Certification Authority
   i:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
 3 s:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
   i:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root

So there is apparently a self signed cert in the cert chain but Android is happy with it.

**Comment by lukefanning** [comment]
Ok appears as though IOS always logs that in debug. See https://github.com/square/SocketRocket/blob/master/SocketRocket/SRWebSocket.m (assuming this is the right source!)

**Comment by fender** [comment]
Excellent!

**Comment by fender** [comment]
@chrisdew Please close this one. 👍
