### ISSUE TITLE
Alter timeout

### ISSUE THREAD

**Issue by fender** [chrisdew/jsonspace#52]
@chrisdew I think this got lost in the comments of another ticket but we need to adjust the timeout:

1. Once a timeout is reached, immediately disconnect and also unsubscribe them from all channels. Do not wait for the unsubscribe delay.
2. Change the timeout setting to 2 minutes. We want to be a bit more aggressive.

**Comment by chrisdew** [comment]
Yes, you're right, I remember this now.

**Comment by chrisdew** [comment]
The behaviour now should be:

Websocket disconnected, due to 120,000ms timeout - all subscriptions from that connection unsubscribed *immediately*.

Websocket disconnected for any other reason - all subscriptions from that connection unsubscribed *after* 60,000ms.
