### ISSUE TITLE
Timeout bug

### ISSUE THREAD

**Issue by fender** [chrisdew/jsonspace#54]
@chrisdew I don't think timeouts are being cleared when a socket is disconnect. I guess we'll need to clear the timeout here: https://github.com/chrisdew/jsonspace/blob/master/jsonspace/lib/protocol/websocket.js#L35

**Comment by chrisdew** [comment]
Good catch.  What issue did this cause?

**Comment by fender** [comment]
It meant that if a user disconnected then they were unsubscribed after 2
minutes even if their delay was set to something greater.
