### ISSUE TITLE
Pass on new notification params

### ISSUE THREAD

**Issue by fender** [chrisdew/jsonspace#55]
@chrisdew We need to add new params to APN and GCM requests. You just need to pass them on from both `publish` and `notify` messages.

## APN
* expiry
* badge

Example:
```js
apn: {
  expiry: Math.floor(Date.now() / 1000) + 3600, // Expires 1 hour from now.
  badge: 0 // Resets
}
```

## GCM
* time_to_live

Example:
```js
gcm: {
  time_to_live: 3600 // Expires 1 hour from now.
}
```

**Comment by chrisdew** [comment]
The APN code for this is already there - does it not work?
https://github.com/chrisdew/jsonspace/blob/6bfdebdecec210e2133839cdfa62e3947139609d/jsonspace/lib/protocol/apn.js#L14

**Comment by chrisdew** [comment]
Seems to be working, as far as I can tell without real tokens...

<pre>
{"websocket_obj_rx":{"conn_id":"websocket|81.187.221.90:49518|45.79.6.86:8888","data":{"publish":{"channel":"ff","data":"dd","apn":{"expiry":1111,"badge":2},"gcm":{"time_to_live":3333}}}},"id":"2016-04-27T18:50:15.039Z|1|45.79.6.86|16932"}
{"published":{"channel":"ff","username":"user_a","data":"dd","conn_id":"websocket|81.187.221.90:49518|45.79.6.86:8888","apn":{"expiry":1111,"badge":2},"gcm":{"time_to_live":3333}},"id":"2016-04-27T18:50:15.040Z|0|45.79.6.86|16932"}
...
{"apn_obj_tx":{"expiry":1111,"badge":2,"token":"aa","payload":{"published":{"channel":"ff","username":"user_a","data":"dd"},"id":"2016-04-27T18:50:15.040Z|0|45.79.6.86|16932"}},"id":"2016-04-27T18:50:15.043Z|1|45.79.6.86|16932"}
SEND
SENT
{"gcm_obj_tx":{"time_to_live":3333,"token":"bb","payload":{"published":{"channel":"ff","username":"user_a","data":"dd"},"id":"2016-04-27T18:50:15.040Z|0|45.79.6.86|16932"}},"id":"2016-04-27T18:50:15.050Z|0|45.79.6.86|16932"}
GCM SEND
SENDING: Message {
  params:
   { priority: 'high',
     timeToLive: 3333,
     notification:
      { title: 'title',
        icon: 'ic_launcher',
        body: 'body',
        sound: undefined,
        tag: undefined,
        color: undefined,
        click_action: undefined },
     data: { data: [Object] } } }
SENDING: {"params":{"priority":"high","timeToLive":3333,"notification":{"title":"title","icon":"ic_launcher","body":"body"},"data":{"data":{"published":{"channel":"ff","username":"user_a","data":"dd"},"id":"2016-04-27T18:50:15.040Z|0|45.79.6.86|16932"}}}}
to: bb
GCM SENT
</pre>

**Comment by fender** [comment]
Oh, I just assumed it wouldn't be. Sweet. In that case it's just GCM.
