### ISSUE TITLE
Blocked Users

### ISSUE THREAD

**Issue by fender** [chrisdew/jsonspace#57]
@chrisdew Something I overlooked. To abide with iOS App Store regulations, we need to implement a way to block users. Ideally, a user would pass in a `blocked_users` array of usernames when subscribing to a channel. Then, any activity (join/left/members etc) from that user would not be broadcasted to usernames that were blocked. In essence, they become invisible to the users they have blocked.

Is this something fairly easy to implement? Unfortunately we cannot release our app until this is done.

**Comment by chrisdew** [comment]
Yes, I can do this, this weekend, as part of the monthly retainer.

I assume you mean:
In essence, the users they have blocked become invisible to them.

instead of:
In essence, they become invisible to the users they have blocked.

**Comment by chrisdew** [comment]
Does this need to apply to "watches" too?

**Comment by fender** [comment]
Well, if Fred has Bob listed in his blocked user list then Bob should never
see any activity from Fred. Otherwise Bob knows when Fred is online and can
abuse him by sending 'notify' messages etc.

Fred can still see Bob but we can handle hiding Bob on the client side if
we want to. Make sense?

**Comment by chrisdew** [comment]
Thanks for the clarification., I was about to implement it the other way around - I was going to build an "ignore" feature, rather than the "hidefrom" feature which I now know you want.

I will explicitly call this feature "hidefrom", as "blocked" could mean either or both.

Logically, "hidefrom" will work as "extra" - the "hidefrom" list sent in the latest subscribe will override any earlier list.  ("hidefrom" is a associated with a username across all aubscriptions, whereas "ignore" could/would be per-subscription.)

**Comment by chrisdew** [comment]
This all seems to be working...  Each published message has an (internal) "hidefrom" property which is a copy of the "hidefrom" of the subscription which did the publish.

i.e.
1. user_a subscribes, hiding from user_b
2. user_a publishes message_0
3. user_a unsubscribes
4. user_a subscribes, not hiding from user_b
5. user_a publishes message_1
6. user_b subscribes, requesting history

user_b will be told about message_1, but not told about message_0, as user_a was hiding from him at the time message_0 was published.

**Comment by fender** [comment]
@chrisdew Does user B also not see user A join/left/etc messages and not see them appear in the members list?

**Comment by chrisdew** [comment]
Correct.

**Comment by fender** [comment]
@chrisdew This doesn't seem to be working. `Rve4VIJYT4` can see `nYys6lrYoF` in the members list. Here is the subscriber list.

```json
{
  "es": [
    {
      "subscribed": {
        "conn_id": "websocket|127.0.0.1:36026|127.0.0.1:8888",
        "username": "nYys6lrYoF",
        "channel": "es",
        "extra": {
          "displayName": "Scary Terry",
          "language": "es",
          "ability": "beginner",
          "items": [
            "avatar_blue",
            "stripes",
            "mohawk_green",
            null,
            "goggles_blue"
          ],
          "level": 6,
          "interfaceLanguage": "en",
          "hidefrom": [
            "Rve4VIJYT4"
          ]
        },
        "uod_delay": 900000,
        "server": "106.186.121.210",
        "apn": {
          "token": "6572726f72"
        }
      },
      "id": "2016-05-07T08:52:39.817Z|1|106.186.121.210|17348"
    },
    {
      "subscribed": {
        "conn_id": "websocket|127.0.0.1:36032|127.0.0.1:8888",
        "username": "Rve4VIJYT4",
        "channel": "es",
        "extra": {
          "displayName": "Tiny Rick",
          "language": "es",
          "ability": "beginner",
          "items": [
            "avatar_blue",
            "sunglasses_orange",
            "collar_blue"
          ],
          "level": 2,
          "interfaceLanguage": "en"
        },
        "uod_delay": 900000,
        "server": "106.186.121.210",
        "apn": {
          "token": "08d10c33ad74d9ba9ef01226b5a3b97565808375e42da6abc6bdaab671fb1eb5"
        }
      },
      "id": "2016-05-07T08:52:44.084Z|0|106.186.121.210|17348"
    }
  ]
}
```

Also, on the debugger, I am seeing an error as soon as I try to use `hidefrom`.

```
connected:ws://45.79.6.86:8888/pubsub
sent:{"subscribe":{"username":"user_a","channel":"foo","extra":"","hidefrom":["user_b"]}}
websocket closed by server, please refresh page to continue
```

**Comment by chrisdew** [comment]
Still not working.

**Comment by chrisdew** [comment]
Will fix tomorrow.

**Comment by chrisdew** [comment]
This latest crash (on tokyo, this time) was not related to hidefrom, it was a mistake I made in handling https://github.com/chrisdew/jsonspace/issues/58

**Comment by chrisdew** [comment]
Retested, for completeness.


    connected:ws://45.79.6.86:8888/pubsub
    sent:{"subscribe":{"username":"user_a","channel":"ff","extra":"","hidefrom":["user_b"]}}
    rx:{"id":"2016-05-08T05:19:39.658Z|0|45.79.6.86|13575","joined":{"username":"user_a","channel":"ff","extra":""}}
    rx:{"members":{"channel":"ff","list":[{"username":"user_a","extra":""}]}}
    rx:{"id":"2016-05-08T05:19:45.502Z|1|45.79.6.86|13575","joined":{"username":"user_b","channel":"ff","extra":""}}
    rx:{"id":"2016-05-08T05:19:49.213Z|2|45.79.6.86|13575","joined":{"username":"user_c","channel":"ff","extra":""}}
    sent:{"publish":{"channel":"ff","data":"a"}}
    rx:{"published":{"channel":"ff","username":"user_b","data":"b"},"id":"2016-05-08T05:20:13.311Z|2|45.79.6.86|13575"}
    rx:{"published":{"channel":"ff","username":"user_c","data":"c"},"id":"2016-05-08T05:20:19.354Z|2|45.79.6.86|13575"}
    sent:{"unsubscribe":{"username":"user_a","channel":"ff"}}


    connected:ws://45.79.6.86:8888/pubsub
    sent:{"subscribe":{"username":"user_b","channel":"ff","extra":""}}
    rx:{"id":"2016-05-08T05:19:45.502Z|1|45.79.6.86|13575","joined":{"username":"user_b","channel":"ff","extra":""}}
    rx:{"members":{"channel":"ff","list":[{"username":"user_b","extra":""}]}}
    rx:{"id":"2016-05-08T05:19:49.213Z|2|45.79.6.86|13575","joined":{"username":"user_c","channel":"ff","extra":""}}
    sent:{"publish":{"channel":"ff","data":"b"}}
    rx:{"published":{"channel":"ff","username":"user_c","data":"c"},"id":"2016-05-08T05:20:19.354Z|2|45.79.6.86|13575"}
    sent:{"unsubscribe":{"username":"user_b","channel":"ff"}}


    connected:ws://45.79.6.86:8888/pubsub
    sent:{"subscribe":{"username":"user_c","channel":"ff","extra":""}}
    rx:{"id":"2016-05-08T05:19:49.213Z|2|45.79.6.86|13575","joined":{"username":"user_c","channel":"ff","extra":""}}
    rx:{"members":{"channel":"ff","list":[{"username":"user_a","extra":""},{"username":"user_b","extra":""},{"username":"user_c","extra":""}]}}
    rx:{"published":{"channel":"ff","username":"user_a","data":"a"},"id":"2016-05-08T05:20:05.232Z|0|45.79.6.86|13575"}
    rx:{"published":{"channel":"ff","username":"user_b","data":"b"},"id":"2016-05-08T05:20:13.311Z|2|45.79.6.86|13575"}
    sent:{"publish":{"channel":"ff","data":"c"}}
    rx:{"id":"2016-05-08T05:20:51.708Z|0|45.79.6.86|13575","left":{"username":"user_a","channel":"ff","extra":""}}
    rx:{"id":"2016-05-08T05:21:19.449Z|2|45.79.6.86|13575","left":{"username":"user_b","channel":"ff","extra":""}}
    sent:{"unsubscribe":{"username":"user_c","channel":"ff"}}
